name: Cypress tests

on:
  schedule:
    - cron: "0 23 * * 0-4" # UTC 기준 매주 일요일 ~ 수요일 23:00 (11:00 PM)에 실행

  push:
    branches:
      - main

jobs:
  signup_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.9.0"

      - name: Install Dependencies
        run: yarn add cypress@latest

      - name: Run Cypress tests
        run: |
          export TZ="Asia/Seoul"
          yarn cypress run --browser chrome --spec "cypress/e2e/project/signup.cy.js"

      - name: Upload cpress signup test screenshots
        uses: actions/upload-artifact@v2
        with:
          name: cypress-signup_test_screenshots
          path: cypress/screenshots/signup_test

  dataset_upload_test:
    runs-on: ubuntu-latest
    needs: signup_test  # signup_test 작업이 완료될 때까지 대기

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.9.0"

      - name: Install Dependencies
        run: yarn add cypress@latest

      - name: Run Cypress tests
        run: |
          export TZ="Asia/Seoul"
          yarn cypress run --browser chrome --spec "cypress/e2e/project/dataset-upload.cy.js"

  image_project_create_test:
    runs-on: windows-latest
    needs: dataset_upload_test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.9.0'

      - name: Install Dependencies
        run: yarn add cypress@latest

      - name: Run Cypress tests
        run: |
          export TZ="Asia/Seoul"
          yarn cypress run --browser chrome --spec "cypress/e2e/project/image-project-create.cy.js" &&
          yarn cypress run --browser chrome --spec "cypress/e2e/project/image-test-project-create.cy.js"

  record_project_create_test:
    runs-on: windows-latest
    needs: image_project_create_test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.9.0'

      - name: Install Dependencies
        run: yarn add cypress@latest

      - name: Run Cypress tests
        run: |
          export TZ="Asia/Seoul" 
          yarn cypress run --browser chrome --spec "cypress/e2e/Project/record-project-create.cy.js" &&
          yarn cypress run --browser chrome --spec "cypress/e2e/Project/record-test-project-create.cy.js"

  organization_test:
    runs-on: windows-latest
    needs: record_project_create_test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.9.0"

      - name: Install Dependencies
        run: yarn add cypress@latest

      - name: Run Cypress tests
        run: |
          export TZ="Asia/Seoul" 
          yarn cypress run --browser chrome --spec "cypress/e2e/project/organization-create.cy.js" && 
          yarn cypress run --browser chrome --spec "cypress/e2e/project/organization-dataset-upload.cy.js"
