name: Cypress tests

on:
  schedule:
    - cron: "0 23 * * 0-4" # UTC 기준 매주 일요일 ~ 수요일 23:00 (11:00 PM)에 실행

  push:
    branches:
      - main

env:
  TZ: "Asia/Seoul"

jobs:
  signup_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create Screenshots Directory
        run: mkdir -p cypress/screenshots

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.9.0"

      - name: Install Dependencies
        run: yarn add cypress@latest

      - name: Run Cypress tests with retry on failure
        run: |
          # Retry logic
          for run in {1..3}; do
            yarn cypress run --browser chrome --spec "cypress/e2e/project/signup.cy.js"
            # Check if the exit code is 0 (success)
            if [ $? -eq 0 ]; then
              break
            fi
            # Wait for 60 seconds before retrying
            sleep 60
          done

  dataset_upload_test:
    runs-on: ubuntu-latest
    needs: signup_test  # signup_test 작업이 완료될 때까지 대기

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.9.0"

      - name: Install Dependencies
        run: yarn add cypress@latest

      - name: Run Cypress tests
        run: yarn cypress run --browser chrome --spec "cypress/e2e/project/dataset-upload.cy.js"

  image_project_create_test:
    runs-on: ubuntu-latest
    needs: dataset_upload_test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.9.0'

      - name: Install Dependencies
        run: yarn add cypress@latest

      - name: Run Cypress tests
        run: |
          yarn cypress run --browser chrome --spec "cypress/e2e/project/image-project-create.cy.js" &&
          yarn cypress run --browser chrome --spec "cypress/e2e/project/image-test-project-create.cy.js"

  record_project_create_test:
    runs-on: ubuntu-latest
    needs: image_project_create_test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.9.0'

      - name: Install Dependencies
        run: yarn add cypress@latest

      - name: Run Cypress tests
        run: |
          yarn cypress run --browser chrome --spec "cypress/e2e/project/record-project-create.cy.js" &&
          yarn cypress run --browser chrome --spec "cypress/e2e/project/record-test-project-create.cy.js"

  organization_test:
    runs-on: ubuntu-latest
    needs: record_project_create_test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.9.0"

      - name: Install Dependencies
        run: yarn add cypress@latest

      - name: Run Cypress tests
        run: |
          yarn cypress run --browser chrome --spec "cypress/e2e/project/organization-create.cy.js" && 
          yarn cypress run --browser chrome --spec "cypress/e2e/project/organization-dataset-upload.cy.js"

  download_file_test:
    runs-on: ubuntu-latest
    needs: organization_test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.9.0"

      - name: Install Dependencies
        run: yarn add cypress@latest

      - name: Run Cypress tests
        run: |
          yarn cypress run --browser chrome --spec "cypress/e2e/project/download-file.cy.js"
