name: Cypress SignUp Tests

on:
  schedule:
    - cron: '0 23 * * 0-4' 
  push:
      branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install

    - name: Run Cypress Tests and Generate JUnit XML Report
      run: |
        npx cypress run --spec "cypress/e2e/Project/1_SignUp.cy.js,
                                    cypress/e2e/Project/2_User_change_Information.cy.js," --reporter junit --reporter-options "mochaFile=junit/test-results.xml"
        
    - name: Upload JUnit XML Report
      uses: actions/upload-artifact@v2
      with:
        name: SignUp-test-results
        path: junit/SignUp-test-results.xml             