name: Cypress tests

on:
  schedule:
    - cron: "0 23 * * 0-4" # UTC 기준 매주 일요일 ~ 수요일 23:00 (11:00 PM)에 실행

  push:
    branches:
      - main

jobs:
  signup_test:
    runs-on: windows-latest

    env:
      TZ: Asia/Seoul

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.9.0"

      - name: Install Dependencies
        run: yarn add cypress@latest

      - name: Run Cypress tests
        run: yarn cypress run --browser chrome --spec "cypress/e2e/project/signup.cy.js"

  dataset_upload_test:
    runs-on: windows-latest
    env:
      TZ: Asia/Seoul
    needs: signup_test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.9.0"

      - name: Install Dependencies
        run: yarn add cypress@latest

      - name: Run Cypress tests
        run: yarn cypress run --browser chrome --spec "cypress/e2e/project/test.cy.js"

  # image_project_create_test:
  #   runs-on: windows-latest
  #   needs: dataset_upload_test

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v2

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: '20.9.0'

  #     - name: Install Dependencies
  #       run: yarn add cypress@latest

  #     - name: Run Cypress tests
  #       run: |
  #         TZ=Asia/Seoul yarn cypress run --browser chrome --spec "cypress/e2e/project/3.image-project-create.cy.js" &&
  #         TZ=Asia/Seoul yarn cypress run --browser chrome --spec "cypress/e2e/project/4.image-test-project-create.cy.js"

  # record_project_create_test:
  #   runs-on: windows-latest
  #   needs: image_project_create_test

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v2

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: '20.9.0'

  #     - name: Install Dependencies
  #       run: yarn add cypress@latest

  #     - name: Run Cypress tests
  #       run: |
  #         TZ=Asia/Seoul yarn cypress run --browser chrome --spec "cypress/e2e/Project/5.record-project-create.cy.js" &&
  #         TZ=Asia/Seoul yarn cypress run --browser chrome --spec "cypress/e2e/Project/6.record-test-project-create.cy.js"

  organization_test:
    runs-on: windows-latest
    env:
      TZ: Asia/Seoul
    needs: dataset_upload_test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.9.0"

      - name: Install Dependencies
        run: yarn add cypress@latest

      - name: Run Cypress tests
        run: |
          yarn cypress run --browser chrome --spec "cypress/e2e/project/organization-create.cy.js" && 
          yarn cypress run --browser chrome --spec "cypress/e2e/project/organization-dataset-upload.cy.js"
