# name: Cypress tests

# on:
#     schedule:
#         - cron: '0 23 * * 0-4' # UTC 기준 매주 일요일 ~ 수요일 23:00 (11:00 PM)에 실행 (KCT: 8:00 AM)

#     push:
#         branches:
#             - main

# env:
#     TZ: 'Asia/Seoul'

# jobs:
#     onprem_signup_test:
#         runs-on: ubuntu-latest
#         container:
#             image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1

#         steps:
#             - uses: actions/checkout@v2

#             - name: Setup Node.js and Install Cypress
#               uses: actions/setup-node@v3
#               with:
#                   node-version: '20.9.0'
#             - run: yarn add cypress@latest

#             - name: Run Cypress tests
#               run: yarn cypress run
#                   --record --key ${{ secrets.CYPRESS_RECORD_KEY }} --browser chrome --spec "cypress/e2e/onprem/onprem-signup.cy.js"

# GitHub Actions Workflow (Cypress tests)

name: Cypress tests

on:
    schedule:
        - cron: '0 23 * * 0-4' # UTC 기준 매주 일요일 ~ 수요일 23:00 (11:00 PM)에 실행 (KCT: 8:00 AM)
    push:
        branches:
            - main

env:
    TZ: 'Asia/Seoul'

jobs:
    # onprem_signup_test:
    #     runs-on: ubuntu-latest
    #     container:
    #         image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1

    #     steps:
    #         - name: Checkout repository
    #           uses: actions/checkout@v2

    #         - name: Setup Node.js and Install Cypress
    #           uses: actions/setup-node@v3
    #           with:
    #               node-version: '20.9.0'
    #         - run: yarn add cypress@latest

    #         - name: Install cURL
    #           run: |
    #               apt-get update && apt-get install -y curl

    #         - name: Grant execute permission to shell scripts
    #           run: |
    #               chmod +x -R ./shell

    #         - name: List shell script files
    #           run: |
    #               ls -la ./shell

    #         - name: Execute shell script
    #           run: |
    #               export CYPRESS_RECORD_KEY="${{ secrets.CYPRESS_RECORD_KEY }}"
    #               ./shell/onprem.sh

    signup_test:
        runs-on: ubuntu-latest
        container:
            image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '20.9.0'
            - run: yarn add cypress@latest

            - name: Install cURL
              run: |
                  apt-get update && apt-get install -y curl

            - name: Grant execute permission to shell scripts
              run: |
                  chmod +x -R ./shell

            - name: List shell script files
              run: |
                  ls -la ./shell

            - name: Execute shell script
              run: |
                  export CYPRESS_RECORD_KEY="${{ secrets.CYPRESS_RECORD_KEY }}"
                  ./shell/schedule.sh

    # onprem_dataset_upload_test:
    #     runs-on: ubuntu-latest
    #     container:
    #         image: cypress/browsers

    #     steps:
    #         - uses: actions/checkout@v2

    #         - name: Setup Node.js and Install Cypress
    #           uses: actions/setup-node@v3
    #           with:
    #               node-version: '20.9.0'
    #         - run: yarn add cypress@latest

    #         - name: Run Cypress tests
    #           run: yarn cypress run
    #               --record --key ${{ secrets.CYPRESS_RECORD_KEY }} --browser chrome --spec "cypress/e2e/onprem/onprem-dataset-upload.cy.js"

    # dataset_upload_test:
    #     runs-on: ubuntu-latest
    #     container:
    #         image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1

    #     steps:
    #         - uses: actions/checkout@v2

    #         - name: Setup Node.js and Install Cypress
    #           uses: actions/setup-node@v3
    #           with:
    #               node-version: '20.9.0'
    #         - run: yarn add cypress@latest

    #         - name: Run Cypress tests
    #           run: yarn cypress run
    #               --record --key ${{ secrets.CYPRESS_RECORD_KEY }} --browser chrome --spec "cypress/e2e/schedule/dataset-upload.cy.js"

    # image_project_create_test:
    #     runs-on: ubuntu-latest
    #     needs: dataset_upload_test

    #     container:
    #         image: cypress/browsers

    #     steps:
    #         - uses: actions/checkout@v2

    #         - name: Setup Node.js and Install Cypress
    #           uses: actions/setup-node@v3
    #           with:
    #               node-version: '20.9.0'
    #         - run: yarn add cypress@latest

    #         - name: Run Cypress tests
    #           run: yarn cypress run --record --key ${{ secrets.CYPRESS_RECORD_KEY }} --browser chrome --spec "cypress/e2e/project/image-project-create.cy.js"

#     image_test_project_create_test:
#         runs-on: ubuntu-latest
#         needs: image_project_create_test

#         container:
#             image: cypress/browsers

#         steps:
#             - uses: actions/checkout@v2

#             - name: Setup Node.js and Install Cypress
#               uses: actions/setup-node@v3
#               with:
#                   node-version: '20.9.0'
#             - run: yarn add cypress@latest

#             - name: Run Cypress tests
#               run: yarn cypress run --record --key ${{ secrets.CYPRESS_RECORD_KEY }} --browser chrome --spec "cypress/e2e/project/image-test-project-create.cy.js"
#               continue-on-error: true

#     record_project_create_test:
#         runs-on: ubuntu-latest
#         needs: image_test_project_create_test

#         container:
#             image: cypress/browsers

#         steps:
#             - uses: actions/checkout@v2

#             - name: Setup Node.js and Install Cypress
#               uses: actions/setup-node@v3
#               with:
#                   node-version: '20.9.0'
#             - run: yarn add cypress@latest

#             - name: Run Cypress tests
#               run: yarn cypress run --record --key ${{ secrets.CYPRESS_RECORD_KEY }} --browser chrome --spec "cypress/e2e/project/record-project-create.cy.js"
#               continue-on-error: true

#     record_test_project_create_test:
#         runs-on: ubuntu-latest
#         needs: record_project_create_test

#         container:
#             image: cypress/browsers

#         steps:
#             - uses: actions/checkout@v2

#             - name: Setup Node.js and Install Cypress
#               uses: actions/setup-node@v3
#               with:
#                   node-version: '20.9.0'
#             - run: yarn add cypress@latest

#             - name: Run Cypress tests
#               run: yarn cypress run --record --key ${{ secrets.CYPRESS_RECORD_KEY }} --browser chrome --spec "cypress/e2e/project/record-test-project-create.cy.js"
#               continue-on-error: true

#     organization_test:
#         runs-on: ubuntu-latest
#         needs: record_test_project_create_test

#         steps:
#             - uses: actions/checkout@v2

#             - name: Setup Node.js and Install Cypress
#               uses: actions/setup-node@v3
#               with:
#                   node-version: '20.9.0'
#             - run: yarn add cypress@latest

#             - name: Run Cypress tests
#               run: yarn cypress run --record --key ${{ secrets.CYPRESS_RECORD_KEY }} --browser chrome --spec "cypress/e2e/project/organization-create.cy.js"
#               continue-on-error: true

#     organization_dataset_upload_test:
#         runs-on: ubuntu-latest
#         needs: organization_test

#         steps:
#             - uses: actions/checkout@v2

#             - name: Setup Node.js and Install Cypress
#               uses: actions/setup-node@v3
#               with:
#                   node-version: '20.9.0'
#             - run: yarn add cypress@latest

#             - name: Run Cypress tests
#               run: yarn cypress run --record --key ${{ secrets.CYPRESS_RECORD_KEY }} --browser chrome --spec "cypress/e2e/project/organization-dataset-upload.cy.js"
#               continue-on-error: true

# download_file_test:
#     runs-on: ubuntu-latest
#     needs: organization_dataset_upload_test

#     steps:
#         - uses: actions/checkout@v2

#         - name: Setup Node.js and Install Cypress
#           uses: actions/setup-node@v3
#           with:
#               node-version: '20.9.0'
#         - run: yarn add cypress@latest

#         - name: Run Cypress tests
#           run: yarn cypress run --record --key ${{ secrets.CYPRESS_RECORD_KEY }} --browser chrome --spec "cypress/e2e/project/download-file.cy.js"
#           continue-on-error: true

# inference-service-create_test:
#     runs-on: ubuntu-latest
#     needs: organization_dataset_upload_test

#     steps:
#         - uses: actions/checkout@v2

#         - name: Setup Node.js and Install Cypress
#           uses: actions/setup-node@v3
#           with:
#               node-version: '20.9.0'
#         - run: yarn add cypress@latest

#         - name: Run Cypress tests
#           run: yarn cypress run --record --key ${{ secrets.CYPRESS_RECORD_KEY }} --browser chrome --spec "cypress/e2e/project/inference-service-create.cy.js"
#           continue-on-error: true
