name: Cypress tests

on:
  schedule:
    - cron: '0 23 * * 0-4' 
  push:
      branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.9.0'

    - name: Install Dependencies
      run: npm install cypress@latest

    - name: Run Cypress tests 
      run: TZ=Asia/Seoul npx cypress run --browser chrome --spec "cypress/e2e/Project/3.image-test-project-create.cy.js"