name: Cypress tests

on:
  schedule:
    - cron: '0 23 * * 0'        # 매주 일요일 23:00 (11:00 PM)에 실행
    - cron: '10 23 * * 0'      # 매주 일요일 23:10 (11:10 PM)에 실행
    - cron: '30 23 * * 0' 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'  # 적절한 노드 버전을 선택하세요

    - name: Install Dependencies
      run: yarn add cypress@latest

    - name: Run Cypress tests 
      run: TZ=Asia/Seoul yarn cypress run --browser chrome --spec "cypress/e2e/Project/1.signup.cy.js"
      
  dataset_upload_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # 적절한 노드 버전을 선택하세요

      - name: Install Dependencies
        run: yarn add cypress@latest

      - name: Run Cypress tests 
        run: TZ=Asia/Seoul yarn cypress run --browser chrome --spec "cypress/e2e/Project/2.dataset-upload.cy.js"
        
  project_create_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # 적절한 노드 버전을 선택하세요

      - name: Install Dependencies
        run: yarn add cypress@latest

      - name: Run Cypress tests 
        run: |
          TZ=Asia/Seoul yarn cypress run --browser chrome --spec "cypress/e2e/Project/3.image-project-create.cy.js" && 
          TZ=Asia/Seoul yarn cypress run --browser chrome --spec "cypress/e2e/Project/4.image-test-project-create.cy.js" && 
          TZ=Asia/Seoul yarn cypress run --browser chrome --spec "cypress/e2e/Project/5.record-project-create.cy.js" && 
          TZ=Asia/Seoul yarn cypress run --browser chrome --spec "cypress/e2e/Project/6.record-test-project-create.cy.js" && 
          TZ=Asia/Seoul yarn cypress run --browser chrome --spec "cypress/e2e/Project/7.organization-create.cy.js" && 
          TZ=Asia/Seoul yarn cypress run --browser chrome --spec "cypress/e2e/Project/8.organization-dataset-upload.cy.js"
